//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchemaExtractor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchemaExtractor.Resources.SqlQueries", typeof(SqlQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	rrc.&quot;RDB$CONSTRAINT_NAME&quot; AS LeftConstraintName,
        ///	rc.&quot;RDB$CONST_NAME_UQ&quot; AS RightConstraintName,
        ///	rrc2.&quot;RDB$RELATION_NAME&quot; AS RightRelationName,
        ///	rrc2.&quot;RDB$INDEX_NAME&quot; AS RightIndexName,
        ///	rc.RDB$UPDATE_RULE AS UpdateRule,
        ///	rc.RDB$DELETE_RULE AS DeleteRule
        ///FROM 
        ///	RDB$RELATION_CONSTRAINTS rrc 
        ///	INNER JOIN RDB$REF_CONSTRAINTS rc ON rc.&quot;RDB$CONSTRAINT_NAME&quot; = rrc.&quot;RDB$CONSTRAINT_NAME&quot;
        ///	INNER JOIN RDB$RELATION_CONSTRAINTS rrc2 ON rrc2.&quot;RDB$CONSTRAINT_NAME&quot; = rc.RDB$CONST_NAME_UQ 
        ///WHERE 
        ///	rrc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RdbForeignKeyLink {
            get {
                return ResourceManager.GetString("RdbForeignKeyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	GEN_UUID() AS RdbDependencyId, 
        ///	RDB$DEPENDENT_NAME AS RdbDependentName, 
        ///	RDB$DEPENDED_ON_NAME AS RdbDependedOnName, 
        ///	RDB$FIELD_NAME AS RdbFieldName, 
        ///	RDB$DEPENDENT_TYPE AS RdbDependentType, 
        ///	RDB$DEPENDED_ON_TYPE AS RdbDependedOnType 
        ///FROM 
        ///	RDB$DEPENDENCIES 
        ///WHERE
        ///	RDB$DEPENDENT_NAME = @DEPENDENT_NAME OR RDB$DEPENDED_ON_NAME = @DEPENDENT_NAME
        ///ORDER BY 
        ///	RDB$DEPENDENT_NAME, RDB$DEPENDED_ON_NAME, RDB$FIELD_NAME.
        /// </summary>
        internal static string SyntheticKeyRdbDependency_EQUALS {
            get {
                return ResourceManager.GetString("SyntheticKeyRdbDependency_EQUALS", resourceCulture);
            }
        }
    }
}
