using JetBrains.Annotations;

namespace SchemaExtractor.Entities
{
    [UsedImplicitly]
    public class CheckConstraint
    {
        /// <Summary>
        /// Constraint name, defined by the user or automatically generated by the system
        /// </Summary>
        public string RdbConstraintName { get; set; }
        /// <Summary>
        /// For a CHECK constraint, it is the name of the trigger that enforces this constraint. For a NOT NULL constraint, it is the name of the table the constraint is applied to. For a foreign key constraint, it is the name of the trigger that enforces the ON UPDATE, ON DELETE clauses 
        /// </Summary>
        public string RdbTriggerName { get; set; }
 
        public virtual RelationConstraint RdbRelationConstraint { get; set; }
    }
}
